var settingsJSON = {
    "name": "Globezones",
    "items": [{
        "title": "pref_header_general",
        "items": [{
            "type": "toggle",
            "label": "pref_btdisalert",
            "storage_key": "glob-btdisalert",
            "pebble_key": 0,
            "default": true
        }, {
            "type": "toggle",
            "label": "pref_btrealert",
            "storage_key": "glob-btrealert",
            "pebble_key": 1,
            "default": false
        }]
    }, {
        "title": "first_timezone",
        "items": [{
            "type": "toggle",
            "label": "enabled",
            "storage_key": "glob-timezone_enabled_0",
            "pebble_key": 2,
            "default": true
        }, {
            "type": "timezones",
            "label": "timezone",
            "storage_key": "glob-timezone_0",
            "pebble_key": 3,
            "default": "Europe/Zurich"
        }, {
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-timezone_colour_0",
            "pebble_key": 4,
            "default": "GColorBlue"
        }, {
            "type": "textfield",
            "label": "name",
            "storage_key": "glob-timezone_name_0",
            "pebble_key": 5,
            "hint": "name",
            "default": "ZUR"
        }]
    }, {
        "title": "second_timezone",
        "items": [{
            "type": "toggle",
            "label": "enabled",
            "storage_key": "glob-timezone_enabled_1",
            "pebble_key": 6,
            "default": true
        }, {
            "type": "timezones",
            "label": "timezone",
            "storage_key": "glob-timezone_1",
            "pebble_key": 7,
            "default": "Europe/Zurich"
        }, {
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-timezone_colour_1",
            "pebble_key": 8,
            "default": "GColorBlue"
        }, {
            "type": "textfield",
            "label": "name",
            "storage_key": "glob-timezone_name_1",
            "pebble_key": 9,
            "hint": "name",
            "default": "ZUR"
        }]
    }, {
        "title": "third_timezone",
        "items": [{
            "type": "toggle",
            "label": "enabled",
            "storage_key": "glob-timezone_enabled_2",
            "pebble_key": 10,
            "default": true
        }, {
            "type": "timezones",
            "label": "timezone",
            "storage_key": "glob-timezone_2",
            "pebble_key": 11,
            "default": "Europe/Zurich"
        }, {
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-timezone_colour_2",
            "pebble_key": 12,
            "default": "GColorBlue"
        }, {
            "type": "textfield",
            "label": "name",
            "storage_key": "glob-timezone_name_2",
            "pebble_key": 13,
            "hint": "name",
            "default": "ZUR"
        }]
    }, {
        "title": "colours",
        "items": [{
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-background_colour",
            "pebble_key": 14,
            "default": "GColorBlack"
        }, {
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-map_colour",
            "pebble_key": 15,
            "default": "GColorWhite"
        }, {
            "type": "colour",
            "label": "colour",
            "storage_key": "glob-time_colour",
            "pebble_key": 16,
            "default": "GColorWhite"
        }]
    }]
}