var settingsJSON = {
	"name":"Holidays",
	"items": [
			  {
			  "title":"pref_header_general",
			  "items":[
					   {
					   "type":"toggle",
					   "label":"pref_btdisalert",
					   "storage_key":"btdisalert",
					   "pebble_key":0,
					   "default":true
					   },
					   {
					   "type":"toggle",
					   "label":"pref_btrealert",
					   "storage_key":"btrealert",
					   "pebble_key":1,
					   "default":false
					   }
					   ]
			  },
			  {
			  "title":"weather",
			  "items":[
					   {
					   "type":"toggle",
					   "label":"show_weather",
					   "storage_key":"show_weather",
					   "pebble_key":2,
					   "default":false
					   },
					   {
					   "type":"toggle",
					   "label":"temperature_format_celcius",
					   "storage_key":"use_celsius",
					   "pebble_key":3,
					   "default":false
					   },
					   {
					   "type":"textfield",
					   "label":"custom_location",
					   "storage_key":"custom_location",
					   "pebble_key":4,
					   "hint":"enter_custom_location",
					   "default":""
					   }
					   ]
			  },
			  {
			  "title":"pref_title_lookandfeel",
			  "items":[
					   {
					   "type":"toggle",
					   "label":"day",
					   "storage_key":"day",
					   "pebble_key":5,
					   "default":true
					   },
					   {
					   "type":"toggle",
					   "label":"date",
					   "storage_key":"date",
					   "pebble_key":6,
					   "default":true
					   }
					   ]
			  },
			  {
			  "title":"snowflakes",
			  "items":[
					   {
					   "type":"toggle",
					   "label":"show_snowflakes",
					   "storage_key":"show_snowflakes",
					   "pebble_key":7,
					   "default":false
					   },
					   {
					   "type":"toggle",
					   "label":"shake_to_animate",
					   "storage_key":"shake_to_animate",
					   "pebble_key":8,
					   "default":false
					   },
					   {
					   "type":"list",
					   "label":"amount_of_snowflakes",
					   "storage_key":"amount_of_snowflakes",
					   "pebble_key":9,
					   "list":[
							   "less", "more", "a_lot"
							   ],
					   "default":0
					   }
					   ]
			  },
			  {
			  "title":"pref_header_colours",
			  "items":[
					   {
					   "type":"colour",
					   "label":"text_colour",
					   "storage_key":"text_colour",
					   "pebble_key":10,
					   "default":"GColorBlack"
					   }
					   ]
			  }
			  ]
}